
code = input("请输入数字:")
code = int(code)
a = input("请输入数字：")
a = int(a)
b = input("请输入数字：")
b = int(b)
c = input("请输入数字：")
c = int(c)
d = input("请输入数字：")
d = int(d)
e = input("请输入数字：")
e = int(e)
f = input("请输入数字：")
f = int(f)
g = input("请输入数字：")
g = int(g)
h = input("请输入数字：")
h = int(h)
i = input("请输入数字：")
i = int(i)
print("总和：",code+a+b+c+d+e+f+g+h+i)