from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get(r"E:/course/第二阶段/练习的html/练习的html/上传文件和下拉列表/autotest.html")
time.sleep(1)
driver.find_element_by_xpath("//*[@id='accountID']").send_keys("张三")
time.sleep(2)
driver.find_element_by_xpath("//*[@id='passwordID']").send_keys("123123")
time.sleep(2)
driver.find_element_by_xpath("//*[@id='areaID']").send_keys("天津")
time.sleep(2)
driver.find_element_by_xpath("//*[@id='sexID2']").click()
time.sleep(2)
driver.find_element_by_xpath("//*[@value='spring']").click()
driver.find_element_by_xpath("//*[@value='winter']").click()
time.sleep(1)
driver.find_element_by_xpath("//*[@name='file' and @type='file']").send_keys("E:\新建文件夹\壁纸.jpeg")
time.sleep(2)
driver.find_element_by_xpath("//*[@id='buttonID']").click()
time.sleep(2)
driver.switch_to.alert.accept()
time.sleep(1)
driver.quit()
